/**
 * Bulk upload every image under /public to ImageKit at /pattern-master/...
 * Preserves the folder structure (e.g. public/icons/foo.png -> /pattern-master/icons/foo.png).
 * Resumable: writes imagekit_mapping.json after each batch and skips files
 * already recorded there on re-runs.
 *
 * Run: node upload_public_images_imagekit.js
 */

const fs = require('fs');
const path = require('path');
const { default: ImageKit, toFile } = require('@imagekit/nodejs');

// --- load .env -----------------------------------------------------------
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf-8').split('\n').forEach((line) => {
    const m = line.trim().match(/^([^=]+)=(.*)$/);
    if (!m) return;
    let v = m[2].trim();
    if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
    process.env[m[1].trim()] = v;
  });
}

const ik = new ImageKit({ privateKey: process.env.IMAGEKIT_PRIVATE_KEY });

const PUBLIC_DIR = path.join(__dirname, 'public');
const MAPPING_FILE = path.join(__dirname, 'imagekit_mapping.json');
const BATCH_SIZE = 8;
const VALID_EXTS = ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg'];

// ImageKit folder/file names disallow spaces and '&'. Keep this in sync with
// lib/imageUtils.ts sanitizeIkPath() so URLs generated by the app match.
function sanitize(seg) {
  return seg.replace(/ /g, '_').replace(/&/g, 'and');
}

function findImages(dir, list = []) {
  for (const entry of fs.readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (fs.statSync(full).isDirectory()) {
      findImages(full, list);
    } else if (VALID_EXTS.includes(path.extname(entry).toLowerCase())) {
      list.push(full);
    }
  }
  return list;
}

let mapping = {};
if (fs.existsSync(MAPPING_FILE)) {
  mapping = JSON.parse(fs.readFileSync(MAPPING_FILE, 'utf-8'));
}
const save = () => fs.writeFileSync(MAPPING_FILE, JSON.stringify(mapping, null, 2));

async function uploadOne(absPath) {
  const rel = path.relative(PUBLIC_DIR, absPath).replace(/\\/g, '/');
  if (mapping[rel]) return { skipped: true, rel };

  const parts = rel.split('/').map(sanitize);
  const fileName = parts.pop();
  const folder = '/pattern-master' + (parts.length ? '/' + parts.join('/') : '');

  const buffer = fs.readFileSync(absPath);
  const fileForUpload = await toFile(buffer, fileName);

  const result = await ik.files.upload({
    file: fileForUpload,
    fileName,
    folder,
    useUniqueFileName: false,
    overwrite: true,
  });

  mapping[rel] = result.url;
  return { uploaded: true, rel, url: result.url };
}

(async () => {
  const all = findImages(PUBLIC_DIR);
  console.log(`Found ${all.length} images under public/. Uploading to ImageKit /pattern-master/...`);

  let done = 0, failed = 0;
  for (let i = 0; i < all.length; i += BATCH_SIZE) {
    const batch = all.slice(i, i + BATCH_SIZE);
    await Promise.all(batch.map(async (p) => {
      try {
        const r = await uploadOne(p);
        done++;
        console.log(`[${done}/${all.length}] ${r.skipped ? 'skip ' : 'up   '} ${r.rel}`);
      } catch (e) {
        failed++;
        console.error(`FAIL ${p}: ${e.message}`);
      }
    }));
    save();
  }
  save();
  console.log(`\nDone. uploaded/skipped=${done}  failed=${failed}`);
  console.log(`Mapping written to ${MAPPING_FILE}`);
})().catch((e) => {
  console.error('Fatal:', e);
  save();
  process.exit(1);
});
