import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — BattleExam",
  description:
    "How BattleExam collects, uses, shares, and protects your personal information.",
};

const LAST_UPDATED = "2026-05-20";

export default function PrivacyPolicyPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-12 text-neutral-200">
      <h1 className="mb-2 text-3xl font-bold text-white">Privacy Policy</h1>
      <p className="mb-8 text-sm text-neutral-400">
        Last updated: {LAST_UPDATED}
      </p>

      <section className="mb-8">
        <p className="leading-relaxed">
          This Privacy Policy explains how BattleExam (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) collects, uses,
          shares, and protects information about you when you use the BattleExam
          website at <Link href="/" className="text-blue-400 hover:underline">battleexam.com</Link> and
          the BattleExam Android application (collectively, the &ldquo;Service&rdquo;).
          By using the Service you agree to the practices described here.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">1. Who we are</h2>
        <p className="leading-relaxed">
          BattleExam is an AI-assisted exam preparation platform for Indian
          competitive examinations including GATE, JEE Main, JEE Advanced,
          NEET UG, and UGC NET. For privacy-related questions or requests,
          contact us at{" "}
          <a
            href="mailto:support@battleexam.com"
            className="text-blue-400 hover:underline"
          >
            support@battleexam.com
          </a>
          .
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          2. Information we collect
        </h2>

        <h3 className="mb-2 mt-4 font-semibold text-white">
          2.1 Information you provide
        </h3>
        <ul className="ml-6 list-disc space-y-1 leading-relaxed">
          <li>
            <strong>Account information.</strong> When you sign in with Google,
            we receive your email address, name, and profile picture URL from
            your Google account via our authentication provider (Clerk).
          </li>
          <li>
            <strong>Preferences.</strong> Your selected exam (e.g., GATE) and
            branch (e.g., CSE).
          </li>
          <li>
            <strong>User-generated content.</strong> Notes you write, bookmarks
            you create, mistakes you flag, and feedback you submit.
          </li>
        </ul>

        <h3 className="mb-2 mt-4 font-semibold text-white">
          2.2 Information generated by your use of the Service
        </h3>
        <ul className="ml-6 list-disc space-y-1 leading-relaxed">
          <li>
            <strong>Activity data.</strong> Questions you attempt, your answers,
            scores, mock-test sessions, time spent per question, and progress
            statistics.
          </li>
          <li>
            <strong>Device and log data.</strong> IP address, browser type and
            version, device model and operating system, app version, and
            timestamps of activity. This is collected automatically when you
            use the Service.
          </li>
          <li>
            <strong>Cookies and similar technologies.</strong> We use cookies
            (primarily session cookies set by Clerk) to keep you signed in and
            to remember preferences. We do not currently use third-party
            advertising cookies.
          </li>
        </ul>

        <h3 className="mb-2 mt-4 font-semibold text-white">
          2.3 What we do not collect
        </h3>
        <p className="leading-relaxed">
          We do not collect precise location, contacts, calendar, microphone,
          camera, SMS, or call-log data. The Android app requests only the
          internet permission required to load content.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          3. How we use your information
        </h2>
        <ul className="ml-6 list-disc space-y-1 leading-relaxed">
          <li>To authenticate you and keep your account secure.</li>
          <li>
            To provide and personalize the Service: deliver questions, track
            progress, generate AI explanations, surface practice
            recommendations, and remember your preferences.
          </li>
          <li>
            To analyze aggregate usage so we can improve features, performance,
            and accuracy.
          </li>
          <li>
            To communicate with you about your account, security issues, or
            material changes to the Service.
          </li>
          <li>
            To detect, prevent, and respond to fraud, abuse, or violations of
            our terms.
          </li>
          <li>To comply with legal obligations.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          4. How we share your information
        </h2>
        <p className="mb-3 leading-relaxed">
          We do not sell your personal information. We share it only with the
          following categories of service providers, strictly for the purposes
          described:
        </p>
        <ul className="ml-6 list-disc space-y-2 leading-relaxed">
          <li>
            <strong>Authentication and identity:</strong> Clerk (
            <a
              href="https://clerk.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 hover:underline"
            >
              privacy policy
            </a>
            ) — sign-in, session management, and user records. Google — OAuth
            provider for sign-in (
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 hover:underline"
            >
              Google&apos;s privacy policy
            </a>
            ).
          </li>
          <li>
            <strong>Hosting and infrastructure:</strong> Vercel (web hosting),
            a managed PostgreSQL provider (primary database), Upstash Redis
            (caching), Cloudinary and ImageKit (image storage and delivery),
            and Pusher (realtime mock-test leaderboards).
          </li>
          <li>
            <strong>AI explanation generation:</strong> third-party AI
            providers. When we generate an explanation for a question, the
            question text and any associated images may be sent to these
            providers for processing. We do not send your personal account
            details to these providers as part of explanation generation.
          </li>
          <li>
            <strong>Analytics (aggregate):</strong> internal anonymized
            counters and dashboards for product improvement. No personal
            identifiers are shared with external analytics providers as of the
            date of this policy.
          </li>
          <li>
            <strong>Legal and safety:</strong> we may disclose information to
            comply with a lawful request from a competent authority, to
            protect our rights, or to investigate fraud or abuse.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          5. Data retention
        </h2>
        <p className="leading-relaxed">
          We retain your account information and activity data for as long as
          your account is active. If you delete your account (see Section 6),
          we permanently delete your personal data and associated content
          (attempts, bookmarks, notes, preferences) from our primary database
          immediately, and from backups within 30 days. Aggregated or
          anonymized data that cannot be linked back to you may be retained
          for analytics.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          6. Your rights and choices
        </h2>
        <p className="mb-3 leading-relaxed">You can, at any time:</p>
        <ul className="ml-6 list-disc space-y-2 leading-relaxed">
          <li>
            <strong>Delete your account and data.</strong> Sign in and visit{" "}
            <Link href="/account" className="text-blue-400 hover:underline">
              battleexam.com/account
            </Link>
            , or open the Android app, tap your profile, and choose
            &ldquo;Account &amp; deletion&rdquo;. Deletion is immediate and
            irreversible. The same URL also works from any browser, including
            if you have already uninstalled the app.
          </li>
          <li>
            <strong>Access or correct your information.</strong> Most account
            details can be updated by signing in. For anything else, email{" "}
            <a
              href="mailto:support@battleexam.com"
              className="text-blue-400 hover:underline"
            >
              support@battleexam.com
            </a>
            .
          </li>
          <li>
            <strong>Export your data.</strong> Email us and we will provide a
            copy of your account data within 30 days.
          </li>
          <li>
            <strong>Withdraw consent.</strong> Delete your account to revoke
            consent to data processing under this policy.
          </li>
        </ul>
        <p className="mt-3 leading-relaxed">
          If you are located in a jurisdiction with additional rights (for
          example under India&apos;s Digital Personal Data Protection Act,
          2023, or the EU GDPR), you may have rights to lodge a complaint with
          a supervisory authority in addition to contacting us directly.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          7. Children&apos;s privacy
        </h2>
        <p className="leading-relaxed">
          The Service is intended for users aged 13 and above. We do not
          knowingly collect personal information from children under 13. If
          you believe a child under 13 has provided us with personal
          information, please email{" "}
          <a
            href="mailto:support@battleexam.com"
            className="text-blue-400 hover:underline"
          >
            support@battleexam.com
          </a>{" "}
          and we will delete it.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">8. Security</h2>
        <p className="leading-relaxed">
          We use industry-standard measures to protect your information,
          including HTTPS in transit, encrypted database connections, and
          access controls. Authentication credentials are managed by Clerk —
          we never see or store your Google password. No system is perfectly
          secure; please use a strong, unique password on your Google account
          and report any suspected compromise to{" "}
          <a
            href="mailto:support@battleexam.com"
            className="text-blue-400 hover:underline"
          >
            support@battleexam.com
          </a>
          .
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          9. International data transfers
        </h2>
        <p className="leading-relaxed">
          BattleExam operates primarily in India. Some of our service
          providers (including Clerk, Vercel, Google, Cloudinary, ImageKit,
          Pusher, Upstash, and the third-party AI providers referenced in
          Section 4) may process data in jurisdictions outside India,
          including the United States and the European Union. We rely on
          these providers&apos; own data-protection commitments and standard
          contractual terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">
          10. Changes to this policy
        </h2>
        <p className="leading-relaxed">
          We may update this Privacy Policy from time to time. When we make
          material changes we will update the &ldquo;Last updated&rdquo; date
          at the top and, where appropriate, notify you in-app or by email.
          Continued use of the Service after a change constitutes acceptance
          of the revised policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-xl font-semibold text-white">11. Contact</h2>
        <p className="leading-relaxed">
          Questions, requests, or complaints about this policy or our handling
          of your information can be sent to{" "}
          <a
            href="mailto:support@battleexam.com"
            className="text-blue-400 hover:underline"
          >
            support@battleexam.com
          </a>
          . We aim to respond within 7 business days.
        </p>
      </section>
    </article>
  );
}
