// app/sitemap.ts
//
// Splits one giant sitemap into a sitemap index (next/16 `generateSitemaps`).
// Each child sitemap stays well under Google's 50 000-URL / 50 MB limit, and
// silently-failed Prisma queries are now logged so we notice when a content
// type stops being submitted.
//
// IMPORTANT: per-question pages (pyq-*, gq-*, spyq-*) are now `noindex` —
// they're thin and the same content lives on the rich topic pages. Per
// Google's guidance, noindex URLs do NOT belong in sitemaps. The buckets
// previously named `pyq-N`, `gq-N`, `spyq-N` have been removed entirely.
//
// Output URLs:
//   /sitemap.xml         → sitemap index (auto-generated by Next from
//                          `generateSitemaps`)
//   /sitemap/0.xml       → hub: static, exam/subject/topic, mock landing
//   /sitemap/mock-N.xml  → individual mock test instances, chunked

import type { MetadataRoute } from "next";
import { prisma } from "@/lib/prisma";
import { toSlug, buildExamSlug } from "@/lib/seo";

export const dynamic = "force-dynamic";

const BASE = "https://battleexam.com";
const CHUNK_SIZE = 10_000; // generous headroom under the 50K cap

type Chunkable = "mock";

// Log + swallow so a single failed table doesn't tank the whole sitemap, but
// we get a Vercel log line instead of a silent empty bucket.
function logFail(label: string) {
  return (e: unknown) => {
    console.error(`[sitemap] ${label} query failed:`, e);
    return [] as never[];
  };
}

async function getCounts(): Promise<Record<Chunkable, number>> {
  const [mock] = await Promise.all([
    prisma.mockTestTemplate.count().catch((e) => {
      console.error("[sitemap] mock count failed:", e);
      return 0;
    }),
  ]);
  return { mock };
}

function chunkCount(rows: number): number {
  return Math.max(1, Math.ceil(rows / CHUNK_SIZE));
}

export async function generateSitemaps(): Promise<{ id: string }[]> {
  const counts = await getCounts();
  const ids: { id: string }[] = [{ id: "0" }]; // hub

  (["mock"] as const).forEach((kind) => {
    if (counts[kind] > 0) {
      for (let i = 0; i < chunkCount(counts[kind]); i++) {
        ids.push({ id: `${kind}-${i}` });
      }
    } else {
      console.warn(`[sitemap] ${kind} bucket is empty — skipping`);
    }
  });

  return ids;
}

// ────────────────────────────────────────────────────────────────────────────
// Bucket builders
// ────────────────────────────────────────────────────────────────────────────

async function buildHubSitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: BASE,                    lastModified: now, changeFrequency: "weekly", priority: 1.0 },
    { url: `${BASE}/sign-up`,       lastModified: now, changeFrequency: "yearly", priority: 0.7 },
    { url: `${BASE}/sign-in`,       lastModified: now, changeFrequency: "yearly", priority: 0.5 },
    { url: `${BASE}/practice`,      lastModified: now, changeFrequency: "daily",  priority: 0.95 },
    { url: `${BASE}/mock-tests`,    lastModified: now, changeFrequency: "daily",  priority: 0.95 },
  ];

  const mockTemplates = await prisma.mockTestTemplate
    .findMany({ select: { exam_type: true, branch: true } })
    .catch(logFail("mock landing"));

  const mockLandingPages: MetadataRoute.Sitemap = [];
  const seenExam = new Set<string>();
  const seenExamBranch = new Set<string>();
  for (const t of mockTemplates) {
    if (!seenExam.has(t.exam_type)) {
      seenExam.add(t.exam_type);
      mockLandingPages.push({
        url: `${BASE}/mock-tests/${toSlug(t.exam_type)}`,
        lastModified: now,
        changeFrequency: "weekly",
        priority: 0.85,
      });
    }
    const branchKey = `${t.exam_type}::${t.branch || "All Subjects"}`;
    if (!seenExamBranch.has(branchKey)) {
      seenExamBranch.add(branchKey);
      mockLandingPages.push({
        url: `${BASE}/mock-tests/${toSlug(t.exam_type)}/${toSlug(t.branch || "All Subjects")}`,
        lastModified: now,
        changeFrequency: "weekly",
        priority: 0.8,
      });
    }
  }

  const examRows = await prisma.pattern
    .findMany({ select: { exam_type: true, branch: true }, distinct: ["exam_type", "branch"] })
    .catch(logFail("exam hub"));
  const examPages: MetadataRoute.Sitemap = examRows.map((r) => ({
    url: `${BASE}/${buildExamSlug(r.exam_type, r.branch)}`,
    lastModified: now,
    changeFrequency: "weekly",
    priority: 0.95,
  }));

  const subjectRows = await prisma.pattern
    .findMany({
      select: { exam_type: true, branch: true, subject: true },
      distinct: ["exam_type", "branch", "subject"],
    })
    .catch(logFail("subject hub"));
  const subjectPages: MetadataRoute.Sitemap = subjectRows.map((r) => ({
    url: `${BASE}/${buildExamSlug(r.exam_type, r.branch)}/${toSlug(r.subject)}`,
    lastModified: now,
    changeFrequency: "weekly",
    priority: 0.9,
  }));

  const topicRows = await prisma.pattern
    .findMany({ select: { exam_type: true, branch: true, subject: true, topic_name: true } })
    .catch(logFail("topic hub"));
  const topicPages: MetadataRoute.Sitemap = topicRows.map((r) => ({
    url: `${BASE}/${buildExamSlug(r.exam_type, r.branch)}/${toSlug(r.subject)}/${toSlug(r.topic_name)}`,
    lastModified: now,
    changeFrequency: "weekly",
    priority: 0.85,
  }));

  return [...staticPages, ...mockLandingPages, ...examPages, ...subjectPages, ...topicPages];
}

async function buildMockChunk(offset: number): Promise<MetadataRoute.Sitemap> {
  const rows = await prisma.mockTestTemplate
    .findMany({
      select: { id: true, exam_type: true, branch: true, created_at: true },
      orderBy: { id: "asc" },
      skip: offset,
      take: CHUNK_SIZE,
    })
    .catch(logFail(`mock chunk @${offset}`));

  return rows.map((t) => ({
    url: `${BASE}/mock-tests/${toSlug(t.exam_type)}/${toSlug(t.branch || "All Subjects")}/${t.id}`,
    lastModified: t.created_at,
    changeFrequency: "monthly" as const,
    priority: 0.75,
  }));
}

// ────────────────────────────────────────────────────────────────────────────
// Entry point — Next 16 passes `id` as Promise<string>
// ────────────────────────────────────────────────────────────────────────────

export default async function sitemap({
  id,
}: {
  id: Promise<string>;
}): Promise<MetadataRoute.Sitemap> {
  const sitemapId = await id;

  if (sitemapId === "0") return buildHubSitemap();

  const dashIdx = sitemapId.lastIndexOf("-");
  if (dashIdx === -1) {
    console.error(`[sitemap] unknown id: ${sitemapId}`);
    return [];
  }
  const kind = sitemapId.slice(0, dashIdx) as Chunkable;
  const chunkIdx = parseInt(sitemapId.slice(dashIdx + 1), 10);
  if (Number.isNaN(chunkIdx)) {
    console.error(`[sitemap] non-numeric chunk index in id: ${sitemapId}`);
    return [];
  }
  const offset = chunkIdx * CHUNK_SIZE;

  switch (kind) {
    case "mock": return buildMockChunk(offset);
    default:
      console.error(`[sitemap] unknown kind: ${kind}`);
      return [];
  }
}
