// components/ui/MathHtml.tsx
//
// Option B consumer. Renders pre-rendered KaTeX/markdown HTML stored in the DB.
// Falls back to the live <MathRenderer> when no stored HTML exists (un-backfilled
// rows, or rows below the current RENDER_VERSION) so the UI is never broken
// during/after a renderer change.
//
// The stored string is the INNER markup produced by lib/math/renderHtml; we wrap
// it in the same `.math-renderer` div MathRenderer uses, so output is identical.
//
// XSS note: `html` is generated by our own trusted pipeline (lib/math/renderHtml)
// from our own scraped content — never from user input. Do not route
// user-submitted text through this without sanitising first.

import type { CSSProperties } from "react";
import MathRenderer from "@/components/ui/MathRenderer";

interface MathHtmlProps {
  /** Pre-rendered inner HTML from lib/math/renderHtml. Null/empty → fallback. */
  html?: string | null;
  /** Raw source content, used for the live-render fallback. */
  raw: string;
  className?: string;
  style?: CSSProperties;
}

export default function MathHtml({ html, raw, className, style }: MathHtmlProps) {
  if (html) {
    return (
      <div
        className={`math-renderer ${className ?? ""}`}
        style={style}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    );
  }
  return <MathRenderer content={raw} className={className} style={style} />;
}
