"use client";
import { useState, useEffect, useCallback, useRef } from "react";
import { Loader2, AlertTriangle } from "lucide-react";
import { useUser } from "@clerk/nextjs";
import { deleteMockTest } from "@/app/actions/admin";
import {
  EXAM_CONFIGS, getExamConfig, scaleExamConfig, clampRandomCount,
  type ExamType, type ExamConfig, type SectionConfig,
} from "@/lib/examConfigs";
import TestEngine, { type TestQuestion, type SubmitAnswer } from "@/components/test/TestEngine";
import TestAnalysis, { type ResultData } from "@/components/test/TestAnalysis";
import { trackPageView } from "@/lib/analytics";
import { clearLocalDraft } from "@/lib/localDraft";
import { BE } from "@/lib/theme";
import { isAdmin as checkIsAdmin } from "@/lib/admin";
import { useSearchParams, useRouter, usePathname } from "next/navigation";
import React from "react";
import SetupPhase from "./SetupPhase";
import BriefPhase from "./BriefPhase";
import { buildResultData } from "./mockTestUtils";

/* ─────────────── Types ─────────────── */
type Phase = "setup" | "brief" | "loading" | "test" | "submitting" | "results";

/** Starting size for a random paper — the cap when a single subject is picked. */
const DEFAULT_RANDOM_COUNT = 30;

/** Paper shape as generated by the server: authoritative over the exam config. */
interface PaperShape {
  durationSecs: number;
  sections: SectionConfig[];
}

export interface SeededMock {
  id: string;
  mock_number: number;
  title: string;
  total_questions: number;
  max_score: number;
  duration_secs: number;
  exam_type?: string;
  branch?: string | null;
  session?: {
    id: string;
    score: number;
    max_score: number;
    correct_count: number;
    wrong_count: number;
    skipped_count: number;
    section_scores?: any;
    created_at: string;
  } | null;
}

/* ─────────────── Rail ─────────────── */
function MTRail({ phase }: { phase: Phase }) {
  const stepMap: Record<Phase, number> = {
    setup: 1, brief: 2, loading: 2, test: 3, submitting: 3, results: 4,
  };
  const step = stepMap[phase] ?? 1;
  const all = [
    { n: 1, label: 'Setup' },
    { n: 2, label: 'Brief' },
    { n: 3, label: 'Test' },
    { n: 4, label: 'Analysis' },
  ];
  return (
    <>
      {/* Desktop */}
      <div className="hidden md:flex items-center gap-0 px-6 py-3.5 border-b shrink-0" style={{ borderColor: BE.line, background: BE.surface }}>
        {all.map((s, i) => {
          const active = s.n === step;
          const done = s.n < step;
          const color = active ? BE.accent : done ? BE.good : BE.textDim;
          return (
            <React.Fragment key={s.n}>
              <div className="flex items-center gap-2 shrink-0">
                <div style={{
                  width: 22, height: 22, borderRadius: 11, fontSize: 11, fontWeight: 600,
                  fontFamily: BE.mono, display: 'flex', alignItems: 'center', justifyContent: 'center',
                  background: active ? BE.accent : done ? BE.good + '22' : 'transparent',
                  color: active ? '#fff' : color,
                  border: `1px solid ${active || done ? color : BE.line}`,
                }}>{done ? '✓' : s.n}</div>
                <span style={{ fontSize: 11.5, fontWeight: 500, color, letterSpacing: '0.02em' }}>{s.label}</span>
              </div>
              {i < all.length - 1 && <div className="mx-2.5 flex-1 min-w-[12px] h-[1px]" style={{ background: BE.line }} />}
            </React.Fragment>
          );
        })}
      </div>
      {/* Mobile dots */}
      <div className="flex md:hidden items-center justify-between px-4 py-2.5 border-b shrink-0" style={{ borderColor: BE.line, background: BE.surface }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: BE.textMute }}>Step {step} of 4</div>
        <div className="flex items-center gap-1.5">
          {all.map((s) => {
            const active = s.n === step;
            const done = s.n < step;
            return (
              <div key={s.n} style={{
                width: active ? 16 : 8, height: 8, borderRadius: 4,
                background: active ? BE.accent : done ? BE.good : 'transparent',
                border: `1px solid ${active ? BE.accent : done ? BE.good : BE.line}`,
                transition: 'width 0.2s ease',
              }} />
            );
          })}
        </div>
      </div>
    </>
  );
}

function MTPage({ children, phase, maxWidth = 980 }: { children: React.ReactNode; phase: Phase; maxWidth?: number }) {
  return (
    <div className="be-screen flex flex-col min-h-full" style={{ background: 'var(--bg-base)' }}>
      <MTRail phase={phase} />
      <div className="flex-1 overflow-auto">
        <div style={{ maxWidth, margin: '0 auto', padding: '32px 24px 60px' }}>{children}</div>
      </div>
    </div>
  );
}

/* ─────────────── Main component ─────────────── */
export default function MockTestPage() {
  const searchParams = useSearchParams();
  const urlTestId = searchParams.get("id");
  const urlSessionId = searchParams.get("sessionId");

  const [phase, setPhase] = useState<Phase>("loading");
  const [selectedExam, setSelectedExam] = useState<ExamType | null>(null);
  const [selectedBranch, setSelectedBranch] = useState<string | null>(null);
  const [selectedMode, setSelectedMode] = useState<"seeded" | "random" | null>(null);
  const [selectedMock, setSelectedMock] = useState<SeededMock | null>(null);
  const [selectedSubjects, setSelectedSubjects] = useState<string[]>([]);
  const [availableSubjects, setAvailableSubjects] = useState<string[]>([]);
  const [randomCount, setRandomCount] = useState(DEFAULT_RANDOM_COUNT);
  const [seededMocks, setSeededMocks] = useState<SeededMock[]>([]);
  const [paperCounts, setPaperCounts] = useState<{ exam_type: string; branch: string | null; count: number }[]>([]);
  const [mockSearch, setMockSearch] = useState("");
  const [briefAgreed, setBriefAgreed] = useState(false);
  const { user } = useUser();
  const userEmail = user?.primaryEmailAddress?.emailAddress?.toLowerCase();
  const isAdmin = checkIsAdmin(userEmail);

  const [questions, setQuestions] = useState<TestQuestion[]>([]);
  const [paperShape, setPaperShape] = useState<PaperShape | null>(null);
  const [mockTestId, setMockTestId] = useState<string | null>(null);
  const [mockTestTitle, setMockTestTitle] = useState("");
  const [result, setResult] = useState<ResultData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const [draftId, setDraftId] = useState<string | null>(null);
  const [serverExpiresAt, setServerExpiresAt] = useState<string | null>(null);
  const [initialDraftState, setInitialDraftState] = useState<Record<string, any> | null>(null);

  const hasAttemptedHydration = useRef(false);

  const router = useRouter();
  const pathname = usePathname();
  const targetPhaseRef = useRef<Phase>("loading");

  const goTo = useCallback((p: Phase, replace = false, mockId?: string, sessionId?: string) => {
    const stepMap: Partial<Record<Phase, number>> = { setup: 1, brief: 2, test: 3, results: 4 };
    const step = stepMap[p];
    targetPhaseRef.current = p;
    const params = new URLSearchParams();
    if (step && step > 1) params.set("step", String(step));
    if (mockId) params.set("id", mockId);
    // Stamp the session id on the results URL so a remount (e.g. navigating to
    // /review and pressing Back) re-hydrates straight into the analysis page
    // instead of falling through to the Brief step.
    if (sessionId && !sessionId.startsWith("local-")) params.set("sessionId", sessionId);
    const query = params.toString();
    const url = query ? `${pathname}?${query}` : pathname;
    if (replace) router.replace(url, { scroll: false });
    else router.push(url, { scroll: false });
    setPhase(p);
  }, [router, pathname]);

  // Listen to popstate (browser back/forward) directly instead of reacting to
  // searchParams changes — searchParams also updates on programmatic router.push,
  // causing races where a queued back-navigation snaps the phase back to setup
  // right after the user manually moved forward.
  useEffect(() => {
    const onPop = () => {
      if (targetPhaseRef.current === "loading") return;
      const url = new URL(window.location.href);
      const step = parseInt(url.searchParams.get("step") ?? "1", 10) || 1;
      const phaseStepMap: Partial<Record<Phase, number>> = {
        setup: 1, brief: 2, loading: 2, test: 3, submitting: 3, results: 4,
      };
      const targetStep = phaseStepMap[targetPhaseRef.current] ?? 1;
      if (step >= targetStep) return;
      const newPhase: Phase = step === 2 && targetPhaseRef.current === "test" ? "brief" : "setup";
      targetPhaseRef.current = newPhase;
      setPhase(newPhase);
    };
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }, []);

  useEffect(() => {
    if (hasAttemptedHydration.current) return;
    hasAttemptedHydration.current = true;

    const init = async () => {
      if (urlSessionId) {
        try {
          const r = await fetch(`/api/test/history/${urlSessionId}`);
          const data = await r.json();
          if (r.ok && data.session) {
            const s = data.session;
            const breakdown: any[] = Array.isArray(s.answers) ? s.answers : [];
            setSelectedExam(s.exam_type as ExamType);
            setMockTestTitle(s.mock_test?.title ?? "Mock Test");
            setMockTestId(s.mock_test_id ?? null);
            setResult(buildResultData(breakdown, {
              score: s.score, maxScore: s.max_score,
              correctCount: s.correct_count, wrongCount: s.wrong_count,
              skippedCount: s.skipped_count, timeTakenSecs: s.time_taken_secs,
            }, { examType: s.exam_type, mockTestId: s.mock_test_id ?? null }));
            goTo("results", true, s.mock_test_id ?? undefined, urlSessionId);
            return;
          }
        } catch {}
        setPhase("setup");
        return;
      }

      try {
        const r = await fetch("/api/test/session/resume");
        const { draft } = await r.json();
        if (draft?.mockTestId) {
          const qRes = await fetch(`/api/test/generate?templateId=${draft.mockTestId}&exam_type=${draft.examType}`);
          const qData = await qRes.json();
          if (qRes.ok && qData.questions?.length > 0) {
            setDraftId(draft.draftId);
            setServerExpiresAt(draft.expiresAt);
            setInitialDraftState(draft.state ?? null);
            setSelectedExam(draft.examType as ExamType);
            setSelectedBranch(draft.branch ?? null);
            setQuestions(qData.questions);
            // Rehydrate the paper's own shape — a resumed user-sized random test
            // has neither the exam's default duration nor its full section list.
            if (qData.durationSecs && Array.isArray(qData.sections)) {
              setPaperShape({ durationSecs: qData.durationSecs, sections: qData.sections });
            }
            setMockTestId(qData.mockTestId ?? draft.mockTestId);
            setMockTestTitle(qData.title ?? "Mock Test");
            goTo("test", true);
            return;
          }
        }
      } catch {}

      if (urlTestId) {
        try {
          const r = await fetch(`/api/test/mocks?id=${urlTestId}`);
          const data = await r.json();
          if (data.mock) {
            const m = data.mock;
            setSelectedExam(m.exam_type as ExamType);
            setSelectedBranch(m.branch);
            setSelectedMode("seeded");
            setSelectedMock(m);
            goTo("brief", true);
            return;
          }
        } catch {}
      }

      setPhase("setup");
    };

    init();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const config: ExamConfig | null = selectedExam
    ? getExamConfig(selectedExam, selectedBranch ?? undefined)
    : null;

  const hasBranches = !!(config?.branches?.length);

  // Requested paper size, re-clamped on every render: deselecting subjects lowers
  // the cap, and a stale higher count must not survive that.
  const effectiveRandomCount = clampRandomCount(randomCount, selectedSubjects.length);

  // What the test actually runs on. The server's shape wins once a paper exists;
  // before that (the Brief step) we predict it with the same scaling function.
  const paperConfig: ExamConfig | null = !config
    ? null
    : paperShape
    ? {
        ...config,
        durationSecs: paperShape.durationSecs,
        sections: paperShape.sections,
        totalQuestions: paperShape.sections.reduce((n, s) => n + s.totalQuestions, 0),
        maxScore: paperShape.sections.reduce((n, s) => n + s.maxScore, 0),
      }
    : selectedMode === "random"
    ? scaleExamConfig(config, effectiveRandomCount)
    : selectedMode === "seeded" && selectedMock?.duration_secs
    ? { ...config, durationSecs: selectedMock.duration_secs }
    : config;

  useEffect(() => {
    fetch("/api/test/mocks/counts")
      .then((r) => r.json())
      .then((d) => setPaperCounts(d.counts ?? []))
      .catch(() => {});
  }, []);

  const examPaperTotal = useCallback(
    (et: string) => paperCounts.filter((c) => c.exam_type === et).reduce((s, c) => s + c.count, 0),
    [paperCounts]
  );
  const branchPaperCount = useCallback(
    (et: string, br: string) => paperCounts.find((c) => c.exam_type === et && c.branch === br)?.count ?? 0,
    [paperCounts]
  );

  useEffect(() => {
    if (!selectedExam) return;
    setMockSearch("");
    const params = new URLSearchParams({ exam_type: selectedExam });
    if (selectedBranch) params.set("branch", selectedBranch);
    fetch(`/api/test/subjects?${params}`)
      .then((r) => r.json())
      .then((d) => setAvailableSubjects(d.subjects ?? []))
      .catch(() => {});
    fetch(`/api/test/mocks?${params}`)
      .then((r) => r.json())
      .then((d) => {
        const sorted = [...(d.mocks ?? [])].sort((a, b) => {
          const aTaken = !!a.session, bTaken = !!b.session;
          if (aTaken && !bTaken) return -1;
          if (!aTaken && bTaken) return 1;
          return a.mock_number - b.mock_number;
        });
        setSeededMocks(sorted);
      })
      .catch(() => {});
  }, [selectedExam, selectedBranch]);

  // Back at Setup, any previously generated paper is stale — the user may be
  // about to pick a different size, and the Brief step must predict from the
  // new selection rather than echo the last paper.
  useEffect(() => {
    if (phase === "setup") setPaperShape(null);
  }, [phase]);

  useEffect(() => {
    if (phase === "brief") {
      try { if (localStorage.getItem("pm_brief_agreed") === "true") setBriefAgreed(true); }
      catch {}
    }
  }, [phase]);

  const startTest = useCallback(async () => {
    if (!selectedExam || !selectedMode || !config) return;
    setPhase("loading");
    setError(null);
    const params = new URLSearchParams({ exam_type: selectedExam, mode: selectedMode });
    if (selectedBranch) params.set("branch", selectedBranch);
    if (selectedMode === "seeded" && selectedMock) params.set("mock_number", String(selectedMock.mock_number));
    if (selectedMode === "random") params.set("count", String(effectiveRandomCount));
    selectedSubjects.forEach((s) => params.append("subject", s));
    try {
      const res = await fetch(`/api/test/generate?${params}`);
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Failed to load questions");

      const newMockTestId = data.mockTestId ?? null;
      // The server may deliver fewer questions than asked for when the bank is
      // thin, so the returned shape — not the requested count — drives the test.
      const shape: PaperShape | null = data.durationSecs && Array.isArray(data.sections)
        ? { durationSecs: data.durationSecs, sections: data.sections }
        : null;
      setQuestions(data.questions);
      setPaperShape(shape);
      setMockTestId(newMockTestId);
      setMockTestTitle(data.title ?? config.label ?? "Mock Test");

      if (newMockTestId) {
        try {
          const sRes = await fetch("/api/test/session/start", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              mockTestId: newMockTestId,
              examType: selectedExam,
              branch: selectedBranch,
              durationSecs: shape?.durationSecs
                ?? (selectedMode === "seeded" && selectedMock?.duration_secs
                  ? selectedMock.duration_secs
                  : config.durationSecs),
            }),
          });
          const sData = await sRes.json();
          setDraftId(sData.draftId ?? null);
          setServerExpiresAt(sData.expiresAt ?? null);
          setInitialDraftState(sData.resumed ? (sData.state ?? null) : null);
        } catch {
          setDraftId(null); setServerExpiresAt(null); setInitialDraftState(null);
        }
      }

      goTo("test", false, selectedMock?.id);
      trackPageView();
    } catch (e: any) {
      setError(e.message);
      setPhase("brief");
    }
  }, [selectedExam, selectedBranch, selectedMode, selectedMock, selectedSubjects, effectiveRandomCount, config, goTo]);

  const handleSubmit = useCallback(async (answers: SubmitAnswer[], timeTakenSecs: number) => {
    setSubmitting(true);
    setSubmitError(null);
    try {
      const res = await fetch("/api/test/submit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mockTestId, answers, timeTakenSecs, examType: selectedExam, branch: selectedBranch }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);

      let breakdown: any[] = data.breakdown || [];
      let sessionScore = data;
      if (!data.breakdown && data.sessionId && !data.sessionId.startsWith("local-")) {
        const histRes = await fetch(`/api/test/history/${data.sessionId}`);
        const histData = await histRes.json();
        if (histRes.ok && histData.session) {
          const s = histData.session;
          breakdown = Array.isArray(s.answers) ? s.answers : [];
          sessionScore = {
            score: s.score, maxScore: s.max_score,
            correctCount: s.correct_count, wrongCount: s.wrong_count, skippedCount: s.skipped_count,
            timeTakenSecs: s.time_taken_secs,
          };
        }
      }

      setResult(buildResultData(breakdown, {
        score: sessionScore.score, maxScore: sessionScore.maxScore,
        correctCount: sessionScore.correctCount, wrongCount: sessionScore.wrongCount,
        skippedCount: sessionScore.skippedCount, timeTakenSecs: sessionScore.timeTakenSecs,
      }, { examType: selectedExam ?? undefined, mockTestId }));
      if (draftId) clearLocalDraft(draftId); // submit landed — drop the offline backup
      goTo("results", false, mockTestId ?? undefined, data.sessionId);
    } catch (err: any) {
      setSubmitError(err.message);
    } finally {
      setSubmitting(false);
    }
  }, [mockTestId, selectedExam, selectedBranch, goTo, draftId]);

  const handleRetake = () => {
    goTo("setup");
    setSelectedMode(null); setSelectedMock(null); setBriefAgreed(false);
    setQuestions([]); setPaperShape(null); setResult(null); setMockTestId(null);
    setSubmitError(null); setError(null);
    setDraftId(null); setServerExpiresAt(null); setInitialDraftState(null);
  };

  const loadAnalysis = useCallback(async (mock: SeededMock) => {
    if (!mock.session?.id) return;
    setPhase("loading");
    setError(null);
    try {
      const res = await fetch(`/api/test/history/${mock.session.id}`);
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Failed to load analysis");
      const s = data.session;
      const breakdown: any[] = Array.isArray(s.answers) ? s.answers : [];
      setMockTestTitle(s.mock_test?.title ?? mock.title);
      setResult(buildResultData(breakdown, {
        score: s.score, maxScore: s.max_score,
        correctCount: s.correct_count, wrongCount: s.wrong_count,
        skippedCount: s.skipped_count, timeTakenSecs: s.time_taken_secs,
      }, { examType: s.exam_type, mockTestId: s.mock_test_id ?? mock.id ?? null }));
      goTo("results", false, mock.id, mock.session.id);
    } catch (e: any) {
      setError(e.message);
      goTo("setup", true);
    }
  }, [goTo]);

  const handleDeleteTest = async (mockId: string, title: string) => {
    if (!confirm(`Delete "${title}"? All sessions will be lost.`)) return;
    try {
      await deleteMockTest(mockId);
      setSeededMocks(prev => prev.filter(m => m.id !== mockId));
    } catch (err: any) { alert(err.message); }
  };

  const canContinue = !!(
    selectedExam &&
    (!hasBranches || selectedBranch) &&
    selectedMode &&
    (selectedMode !== "seeded" || selectedMock)
  );

  /* ════════ STEP 1 — Setup ════════ */
  if (phase === "setup") {
    return (
      <MTPage phase={phase} maxWidth={1100}>
        <SetupPhase
          selectedExam={selectedExam}
          selectedBranch={selectedBranch}
          selectedMode={selectedMode}
          selectedMock={selectedMock}
          selectedSubjects={selectedSubjects}
          availableSubjects={availableSubjects}
          randomCount={effectiveRandomCount}
          seededMocks={seededMocks}
          mockSearch={mockSearch}
          config={config}
          hasBranches={hasBranches}
          isAdmin={isAdmin}
          canContinue={canContinue}
          examPaperTotal={examPaperTotal}
          branchPaperCount={branchPaperCount}
          onSelectExam={(exam) => {
            setSelectedExam(exam);
            setSelectedBranch(null);
            setSelectedMode(null);
            setSelectedMock(null);
          }}
          onSelectBranch={(branch) => {
            setSelectedBranch(branch);
            setSelectedMode(null);
            setSelectedMock(null);
          }}
          onSelectMode={(mode) => { setSelectedMode(mode); setSelectedMock(null); }}
          onSelectMock={(mock) => {
            setSelectedMock(mock);
            router.replace(`${pathname}?id=${mock.id}`, { scroll: false });
          }}
          onSearchChange={setMockSearch}
          onSubjectsChange={setSelectedSubjects}
          onRandomCountChange={(n) => setRandomCount(clampRandomCount(n, selectedSubjects.length))}
          onDeleteTest={handleDeleteTest}
          onContinue={() => { setBriefAgreed(false); goTo("brief", false, selectedMock?.id); }}
          onGoToBrief={(mock) => { setBriefAgreed(false); goTo("brief", false, mock.id); }}
          onLoadAnalysis={loadAnalysis}
        />
      </MTPage>
    );
  }

  /* ════════ STEP 2 — Brief ════════ */
  if (phase === "brief" && paperConfig) {
    return (
      <MTPage phase={phase}>
        <BriefPhase
          config={paperConfig}
          selectedExam={selectedExam}
          selectedMode={selectedMode}
          selectedMock={selectedMock}
          briefAgreed={briefAgreed}
          error={error}
          onToggleAgreed={() => setBriefAgreed(v => {
            const next = !v;
            try { localStorage.setItem("pm_brief_agreed", String(next)); } catch {}
            return next;
          })}
          onBack={() => { setError(null); router.back(); }}
          onBeginTest={startTest}
        />
      </MTPage>
    );
  }

  /* ════════ LOADING / SUBMITTING ════════ */
  if (phase === "loading" || phase === "submitting") {
    return (
      <div className="be-screen flex flex-col items-center justify-center gap-4" style={{ background: 'var(--bg-base)' }}>
        <Loader2 size={36} className="animate-spin" style={{ color: BE.accent }} />
        <p style={{ fontSize: 14, color: BE.textDim }}>
          {phase === "submitting"
            ? "Evaluating your answers…"
            : !hasAttemptedHydration.current || questions.length === 0
            ? "Checking for active session…"
            : "Preparing your paper…"}
        </p>
      </div>
    );
  }

  /* ════════ STEP 3 — Test ════════ */
  if (phase === "test" && paperConfig) {
    if (questions.length === 0) {
      return (
        <MTPage phase={phase}>
          <div className="flex flex-col items-center justify-center gap-6 py-20 text-center">
            <AlertTriangle size={40} style={{ color: BE.warn }} />
            <div>
              <div style={{ fontFamily: BE.serif, fontSize: 24, fontWeight: 600, color: BE.text, marginBottom: 8 }}>No questions were loaded.</div>
              <div style={{ fontSize: 14, color: BE.textDim }}>The paper couldn't be generated. Try a different configuration.</div>
            </div>
            <button className="be-btn" onClick={() => { goTo("setup", true); setError(null); setQuestions([]); }}>← Back to Setup</button>
          </div>
        </MTPage>
      );
    }
    return (
      <TestEngine
        questions={questions}
        config={paperConfig}
        branch={selectedBranch ?? undefined}
        mockTestId={mockTestId}
        mockTestTitle={mockTestTitle}
        onSubmit={handleSubmit}
        submitting={submitting}
        submitError={submitError}
        draftId={draftId}
        serverExpiresAt={serverExpiresAt}
        initialState={initialDraftState}
        userName={user?.fullName ?? user?.firstName ?? undefined}
      />
    );
  }

  /* ════════ STEP 4 — Results ════════ */
  if (phase === "results" && result) {
    return <TestAnalysis result={result} onRestart={handleRetake} />;
  }

  return (
    <div className="be-screen flex items-center justify-center" style={{ background: 'var(--bg-base)' }}>
      <Loader2 size={32} className="animate-spin text-muted-foreground" />
    </div>
  );
}
